version: 2

sources:
  - name: jaffle_shop
    database: jaffle_shop
    tables:
      - name: customers
        identifier: jaffle_shop_customers
      - name: orders
        identifier: jaffle_shop_orders